### ISSUE TITLE
res.str is not a function

### ISSUE THREAD

**Issue by metareven** [lleohao/flask-node#2]
Your example does not work as res.str is not a function.

That is, this code does not work:
```
const Flask = require("flask-node").Flask;
const Router = require('flask-node').Router;

let app = new Flask(__dirname);
let mainRoute = new Router();    // similar to flask @route

mainRoute.add("/", function index(req, res) {
    res.str('Hello world');
});

app.run();
```

How are you supposed to return a response?

**Comment by lleohao** [comment]
Sorry, the document has not been updated
I will inform you later when the document is updated

**Comment by lleohao** [comment]
I have update document.
